import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, test, vi } from 'vitest';
import type { PaperPosition } from '../types';
import { PaperPositions } from './PaperPositions';

const position=(decision:PaperPosition['decision_status']='HOLD',closed=false):PaperPosition=>({id:1,symbol:'SPY',option_symbol:'SPY260803C00550000',direction:'call',strategy_mode:'ONE_MIN_0DTE',strategy_version:'parlay-v1',expiration:'2026-08-03',strike:550,quantity:1,entry_option_price:.75,entry_underlying_price:550,total_debit:75,underlying_trigger:551,underlying_invalidation:549,first_underlying_target:553,stretch_underlying_target:555,first_option_target:1.5,stretch_option_target:3,score:91,score_label:'PLAY',entry_reasons:['VWAP reclaimed'],provider_mode:'mock',opened_at:'2026-08-03T14:00:00Z',closed_at:closed?'2026-08-03T15:00:00Z':null,exit_option_price:closed?1.25:null,exit_underlying_price:closed?553:null,exit_reason:closed?'USER CONFIRMED PAPER EXIT':null,lifecycle_status:closed?'CLOSED':'ACTIVE',expired_at:null,current_option_price:closed?1.25:.9,current_underlying_price:closed?553:551,unrealized_pnl:closed?null:15,realized_pnl:closed?50:null,pnl_percent:20,decision_status:closed?'CLOSED':decision,data_freshness:'mock_current',next_action:decision==='HOLD'?'HOLD — SETUP REMAINS ABOVE INVALIDATION':decision==='TAKE_PROFIT'?'TAKE PROFIT — FIRST TARGET REACHED':decision==='EXIT'?'EXIT — RUNNER TARGET REACHED':'DATA UNAVAILABLE — RETAINING LAST KNOWN POSITION STATE',last_marked_at:'2026-08-03T14:01:00Z',paper_only:true});
afterEach(cleanup);

test.each(['HOLD','TAKE_PROFIT','EXIT'] as const)('renders %s management card',decision=>{render(<PaperPositions positions={[position(decision)]} stale={false} onExit={vi.fn()}/>);expect(screen.getByText(decision.replace('_',' '))).toBeInTheDocument();expect(screen.getByRole('heading',{name:'SPY CALL'})).toBeInTheDocument();expect(screen.getByText(/Unrealized P&L/)).toBeInTheDocument()});
test('formats active expiration as a calendar date and opened time in Eastern Time',()=>{render(<PaperPositions positions={[position()]} stale={false} onExit={vi.fn()}/>);expect(screen.getByText('Aug 3, 2026')).toBeInTheDocument();expect(screen.getByText('Aug 3, 2026, 10:00 AM EDT')).toBeInTheDocument()});
test('retains last-known prices with stale warning and data unavailable state',()=>{const item=position('DATA_UNAVAILABLE');item.data_freshness='data_unavailable';render(<PaperPositions positions={[item]} stale onExit={vi.fn()}/>);expect(screen.getByRole('alert')).toHaveTextContent('Retaining');expect(screen.getByText('DATA UNAVAILABLE')).toBeInTheDocument();expect(screen.getByText('$0.90')).toBeInTheDocument();expect(screen.getAllByText('$551.00').length).toBeGreaterThan(0);expect(screen.getByText('$15.00 (20.00%)')).toBeInTheDocument()});

test('separates expired positions and preserves expiration calendar day',()=>{const item=position('EXPIRED');item.lifecycle_status='EXPIRED';item.expired_at='2026-08-04T04:00:00Z';item.unrealized_pnl=null;item.pnl_percent=null;render(<PaperPositions positions={[item]} stale={false} onExit={vi.fn()}/>);expect(screen.getByText('No open paper positions.')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Expired Paper Positions'})).toBeInTheDocument();expect(screen.getByText('Expired Aug 3, 2026')).toBeInTheDocument();expect(screen.getByText('Historical / stale — no settlement price recorded')).toBeInTheDocument();expect(screen.getByText('Last marked Aug 3, 2026, 10:01 AM EDT')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Exit Paper Position'})).not.toBeInTheDocument()});
test('exit action is explicit and closed position moves to recent exits',()=>{const onExit=vi.fn();const {rerender}=render(<PaperPositions positions={[position()]} stale={false} onExit={onExit}/>);fireEvent.click(screen.getByRole('button',{name:'Exit Paper Position'}));expect(onExit).toHaveBeenCalled();rerender(<PaperPositions positions={[position('CLOSED',true)]} stale={false} onExit={onExit}/>);expect(screen.getByRole('heading',{name:'Recent Paper Exits'})).toBeInTheDocument();expect(screen.getByText('Realized $50.00')).toBeInTheDocument()});
test('uses semantic sections and mobile card structure',()=>{render(<PaperPositions positions={[position()]} stale={false} onExit={vi.fn()}/>);expect(screen.getByRole('region',{name:'Open Paper Positions'})).toBeInTheDocument();expect(document.querySelector('.position-grid .position-card')).toBeTruthy()});
