import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, expect, test, vi } from 'vitest';
import type { ParlayCandidate, ParlayResponse, SignalStatus } from '../types';
import { ParlayBoard, ParlaySkeleton } from './ParlayBoard';

const statuses:SignalStatus[]=['BUY','WATCH','MISSED','PASS','PASS','PASS','PASS','PASS','PASS','PASS','PASS','PASS'];
const symbols=['SPY','QQQ','IWM','TSLA','NVDA','AAPL','AMZN','META','MSFT','GOOGL','AVGO','IBIT'];
const candidate=(symbol:string,index:number):ParlayCandidate=>({ranking_position:index+1,symbol,rank:index===0?'PLAY':'PASS',direction:index%2?'put':'call',signal_status:statuses[index],score:90-index,score_label:index===0?'PLAY':'PASS',underlying_price:100,contract:index<3?{symbol,option_symbol:`${symbol}260803C00101000`,expiration:'2026-08-03',strike:101,right:index%2?'put':'call',bid:.4,ask:.45,last:.43,volume:900,open_interest:1200,iv:null,delta:null,gamma:null,theta:null,vega:null,timestamp:'2026-08-03T14:01:00Z',provider:'tradier',data_mode:'live',quote_freshness:'current',verification_status:'verified',verification_reason:'Exact current contract returned by provider chain',actionable:true}:null,contract_cost:index<3?45:null,midpoint:index<3?.43:null,spread_percent:index<3?11:null,entry_low:index<3?.4:null,entry_high:index<3?.48:null,no_chase_price:index<3?.57:null,underlying_trigger:index<3?101:null,underlying_invalidation:index<3?99:null,first_underlying_target:index<3?102:null,stretch_underlying_target:index<3?104:null,first_option_target:index<3?.96:null,stretch_option_target:index<3?1.92:null,reasons:index<3?['Price reclaimed VWAP']:[],rejection_reasons:index>=3?['Trigger not confirmed']:[],unavailable_reason:null,primary_action:index===0?'BUY BELOW $0.48':index===1?'WAIT FOR QQQ BELOW $99.00':index===2?'MISSED — DO NOT CHASE ABOVE $0.57':'PASS — TRIGGER NOT CONFIRMED',generated_at:'2026-08-03T14:00:00Z',data_freshness:'live_current',provider:'tradier',data_mode:'live',quote_freshness:'current',verification_status:'verified',verification_reason:'Exact current contract returned by provider chain',actionable:index<3});
const data:ParlayResponse={provider_status:{provider:'mock',mode:'mock',status:'healthy',delay_seconds:0,latest_timestamp:'2026-07-28T10:00:00-04:00',message:'Mock data'},universe:symbols,candidates:symbols.map(candidate),scanner_health:{candidate_count:12,unavailable_candidate_count:0,provider_status:'healthy'},paper_only:true};
afterEach(cleanup);

test('groups decisions and keeps No Trade collapsed by default',()=>{render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);expect(screen.getByRole('region',{name:'Ready to Trade'})).toHaveTextContent('SPY');expect(screen.getByRole('region',{name:'Waiting Room'})).toHaveTextContent('QQQ');const noTrade=screen.getByText('MISSED, PASS, and unavailable setups').closest('details');expect(noTrade).not.toHaveAttribute('open');expect(screen.getByText('Paper only')).toBeVisible();expect(screen.getByLabelText('Aggregate scanner health')).toHaveTextContent('12 candidates')});

test('shows the complete actionable contract and calendar expiration',()=>{render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);const ready=screen.getByRole('region',{name:'Ready to Trade'});['BUY NOW','SPY260803C00101000','Aug 3, 2026','Current underlying price','Underlying entry','Underlying stop','Underlying target','Expiration','Strike','Option type','Current bid','Option ask','Estimated contract cost','Signal timing','Last updated'].forEach(label=>expect(within(ready).getByText(label)).toBeInTheDocument());expect(within(ready).getByLabelText('call direction')).toHaveTextContent('CALL');expect(within(ready).getByText('Signal timing').closest('span')).toHaveTextContent('10:00 AM EDT');expect(within(ready).getByText('Last updated').closest('span')).toHaveTextContent('10:01 AM EDT')});

test('moves scoring and diagnostics into Why this setup',()=>{render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);const ready=screen.getByRole('region',{name:'Ready to Trade'});const why=within(ready).getByText('Why this setup?').closest('details');expect(why).not.toHaveAttribute('open');fireEvent.click(within(ready).getByText('Why this setup?'));expect(why).toHaveAttribute('open');expect(within(why as HTMLElement).getByText('Score')).toBeInTheDocument();expect(within(why as HTMLElement).getByText('Data freshness')).toBeInTheDocument();expect(within(why as HTMLElement).getByText('Price reclaimed VWAP')).toBeInTheDocument()});

test('uses plain-language no-trade status while preserving candidate values',()=>{render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);fireEvent.click(screen.getByText('MISSED, PASS, and unavailable setups'));expect(screen.getByText('MISSED — DO NOT CHASE')).toBeInTheDocument();expect(screen.getAllByText('NO TRADE').length).toBeGreaterThan(0)});

test('stale warning preserves the decision board and offers retry',()=>{const retry=vi.fn();render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale onRetry={retry}/>);expect(screen.getByRole('alert')).toHaveTextContent('Stale data');expect(screen.getByRole('region',{name:'Ready to Trade'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Retry Parlay board'}));expect(retry).toHaveBeenCalled()});

test('loading skeleton preserves board layout',()=>{render(<ParlaySkeleton/>);expect(screen.getByLabelText('Loading Parlay board')).toBeInTheDocument()});

test('Paper Enter appears on BUY only and invokes entry handler',()=>{const enter=vi.fn();render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()} onPaperEnter={enter}/>);fireEvent.click(screen.getByRole('button',{name:'Paper Enter'}));expect(enter).toHaveBeenCalledWith(expect.objectContaining({symbol:'SPY',signal_status:'BUY'}));expect(screen.getAllByRole('button',{name:'Paper Enter'})).toHaveLength(1)});

test('mock contracts are clearly demo data and cannot be paper entered',()=>{
  const base=candidate('SPY',0);const demoCandidate={...base,actionable:false,provider:'mock',data_mode:'mock',quote_freshness:'unknown',verification_status:'demo',verification_reason:'explicit mock option data',contract:{...base.contract!,actionable:false,provider:'mock',data_mode:'mock' as const,quote_freshness:'unknown' as const,verification_status:'demo' as const,verification_reason:'explicit mock option data'}};
  const demo={...data,provider_status:{...data.provider_status,provider:'mock',mode:'mock',demo_options_enabled:true},candidates:[demoCandidate]};
  render(<ParlayBoard data={demo} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()} onPaperEnter={vi.fn()}/>);
  expect(screen.getByText('DEMO MODE — MOCK OPTION DATA — DO NOT TRADE')).toBeInTheDocument();
  expect(screen.getByText('0 BUY NOW')).toBeInTheDocument();
  expect(screen.queryByRole('button',{name:'Paper Enter'})).not.toBeInTheDocument();
});
