import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, test, vi } from 'vitest';
import type { ParlayCandidate, ParlayResponse, SignalStatus } from '../types';
import { ParlayBoard, ParlaySkeleton } from './ParlayBoard';

const statuses:SignalStatus[]=['BUY','WATCH','MISSED','PASS','PASS','PASS','PASS','PASS','PASS','PASS','PASS','PASS'];
const symbols=['SPY','QQQ','IWM','TSLA','NVDA','AAPL','AMZN','META','MSFT','GOOGL','AVGO','IBIT'];
const candidate=(symbol:string,index:number):ParlayCandidate=>({ranking_position:index+1,symbol,rank:index===0?'PLAY':'PASS',direction:index%2?'put':'call',signal_status:statuses[index],score:90-index,score_label:index===0?'PLAY':'PASS',underlying_price:100,contract:index<3?{symbol,option_symbol:`${symbol} CALL`,expiration:'2026-07-28',strike:101,right:'call',bid:.4,ask:.45,last:.43,volume:900,open_interest:1200,iv:null,delta:null,gamma:null,theta:null,vega:null,timestamp:''}:null,contract_cost:index<3?45:null,midpoint:index<3?.43:null,spread_percent:index<3?11:null,entry_low:index<3?.4:null,entry_high:index<3?.48:null,no_chase_price:index<3?.57:null,underlying_trigger:index<3?101:null,underlying_invalidation:index<3?99:null,first_underlying_target:index<3?102:null,stretch_underlying_target:index<3?104:null,first_option_target:index<3?.96:null,stretch_option_target:index<3?1.92:null,reasons:index<3?['Price reclaimed VWAP']:[],rejection_reasons:index>=3?['Trigger not confirmed']:[],unavailable_reason:null,primary_action:index===0?'BUY BELOW $0.48':index===1?'WAIT FOR QQQ BELOW $99.00':index===2?'MISSED — DO NOT CHASE ABOVE $0.57':'PASS — TRIGGER NOT CONFIRMED',generated_at:'2026-07-28T10:00:00-04:00',data_freshness:'mock_current'});
const data:ParlayResponse={provider_status:{provider:'mock',mode:'mock',status:'healthy',delay_seconds:0,latest_timestamp:'2026-07-28T10:00:00-04:00',message:'Mock data'},universe:symbols,candidates:symbols.map(candidate),paper_only:true};
afterEach(cleanup);

test('renders ranked hero, statuses, provider, paper warning, and all symbols',()=>{render(<ParlayBoard data={data} updated={new Date('2026-07-28T14:00:00Z')} refreshing={false} stale={false} onRetry={vi.fn()}/>);expect(screen.getByText('Best Play Right Now')).toBeInTheDocument();expect(screen.getAllByText('SPY').length).toBeGreaterThan(0);expect(screen.getAllByLabelText('call direction').length).toBeGreaterThan(0);expect(screen.getAllByText('BUY').length).toBeGreaterThan(0);expect(screen.getAllByText('WATCH').length).toBeGreaterThan(0);expect(screen.getAllByText('MISSED — DO NOT CHASE').length).toBeGreaterThan(0);expect(screen.getAllByText('PASS').length).toBeGreaterThan(0);expect(screen.getByText('Paper-only research. No live orders are placed.')).toBeInTheDocument();expect(screen.getByLabelText('Market data status')).toHaveTextContent('MOCK');symbols.forEach(symbol=>expect(screen.getAllByText(symbol).length).toBeGreaterThan(0));expect(screen.queryByText(/probability/i)).not.toBeInTheDocument()});

test('filters locally and expands accessible scanner details',()=>{render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);const buyFilter=screen.getByRole('button',{name:'BUY 1'});fireEvent.click(buyFilter);expect(buyFilter).toHaveAttribute('aria-pressed','true');expect(screen.getByText('1 shown')).toBeInTheDocument();const details=screen.getByRole('button',{name:'Show SPY details'});fireEvent.click(details);expect(details).toHaveAttribute('aria-expanded','true');expect(screen.getAllByText('FIRST CASH-OUT').length).toBeGreaterThan(0)});

test('stale warning preserves board and offers retry',()=>{const retry=vi.fn();render(<ParlayBoard data={data} updated={new Date()} refreshing={false} stale onRetry={retry}/>);expect(screen.getByRole('alert')).toHaveTextContent('Stale data');expect(screen.getByText('Best Play Right Now')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Retry Parlay board'}));expect(retry).toHaveBeenCalled()});

test('loading skeleton preserves board layout',()=>{render(<ParlaySkeleton/>);expect(screen.getByLabelText('Loading Parlay board')).toBeInTheDocument()});

test('all-PASS board shows no-qualified state without a best-play hero',()=>{const passData={...data,candidates:data.candidates.map(item=>({...item,signal_status:'PASS' as const}))};render(<ParlayBoard data={passData} updated={new Date()} refreshing={false} stale={false} onRetry={vi.fn()}/>);expect(screen.getByText('NO QUALIFIED PARLAYS RIGHT NOW')).toBeInTheDocument();expect(screen.queryByText('Best Play Right Now')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Show SPY details'})).toBeInTheDocument()});
