import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { getAnalytics, getDashboard, getJournal } from './api/client';
import type { Analytics, Dashboard, JournalSignal, LiquidityLevels } from './types';
import './style.css';

function Card({title,children,danger=false,id}:{title:string;children:React.ReactNode;danger?:boolean;id?:string}) { return <section id={id} className={`card ${danger?'danger':''}`}><h2>{title}</h2>{children}</section> }
function Metric({label,value}:{label:string;value:React.ReactNode}) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
function formatLevels(values:number[]):string { return values.length ? values.map(value=>value.toFixed(2)).join(', ') : 'None detected'; }
function LiquidityMap({levels}:{levels:Record<string,LiquidityLevels>}) { return <>{Object.entries(levels).map(([symbol,item])=><details key={symbol}><summary>{symbol}</summary><div className="levels"><Metric label="Previous day high / low" value={`${item.previous_day_high.toFixed(2)} / ${item.previous_day_low.toFixed(2)}`}/><Metric label="Opening range high / low" value={`${item.opening_range_high.toFixed(2)} / ${item.opening_range_low.toFixed(2)}`}/><Metric label="Session high / low" value={`${item.session_high.toFixed(2)} / ${item.session_low.toFixed(2)}`}/><Metric label="VWAP" value={item.vwap.toFixed(2)}/><Metric label="Equal highs" value={formatLevels(item.equal_highs)}/><Metric label="Equal lows" value={formatLevels(item.equal_lows)}/></div></details>)}</> }
function EqualLevelOverlays({levels}:{levels:Record<string,LiquidityLevels>}) { const highs=Object.values(levels).flatMap(item=>item.equal_highs); const lows=Object.values(levels).flatMap(item=>item.equal_lows); return <div className="overlay-list">VWAP ✓ &nbsp; OR high/low ✓ &nbsp; Equal highs ({highs.length}) ✓ &nbsp; Equal lows ({lows.length}) ✓</div> }

export function App() {
  const [dashboard,setDashboard]=useState<Dashboard|null>(null);
  const [journal,setJournal]=useState<JournalSignal[]>([]);
  const [analytics,setAnalytics]=useState<Analytics|null>(null);
  const [error,setError]=useState('');
  useEffect(()=>{ Promise.all([getDashboard(),getJournal(),getAnalytics()]).then(([d,j,a])=>{setDashboard(d);setJournal(j);setAnalytics(a)}).catch((reason:Error)=>setError(reason.message)); },[]);
  if(error) return <main><Card title="Unable to load dashboard" danger><p>{error}</p><p>Confirm the FastAPI service is running on port 8000.</p></Card></main>;
  if(!dashboard) return <main className="loading">Loading audited market state…</main>;
  return <main>
    <header><div><p className="eyebrow">RESEARCH & PAPER TRADING</p><h1>0DTE Liquidity Hunter</h1><p>Deterministic SPY, QQQ and IWM liquidity-event scanner.</p></div><div className="header-status"><span className="pill">{String(dashboard.paper_account.mode)}</span><span className="live-disabled">LIVE ORDERS DISABLED</span></div></header>
    <nav>{['command','charts','structured','lottery','journal','analytics'].map(item=><a key={item} href={`#${item}`}>{item}</a>)}</nav>
    <div className="mock-banner"><strong>MOCK DATA — NOT LIVE</strong><span>{dashboard.provider_status.message}</span></div>
    <section id="command" className="quote-row">{dashboard.quotes.map(q=><div className="quote" key={q.symbol}><span>{q.symbol}</span><strong>${q.price.toFixed(2)}</strong><small>{dashboard.directional_bias[q.symbol]}</small></div>)}<div className="quote"><span>VOL PROXY</span><strong>{dashboard.volatility_proxy ?? 'N/A'}</strong><small>{dashboard.market_session} session</small></div></section>
    <div className="grid"><Card title="Feed & Account"><Metric label="Provider" value={dashboard.provider_status.provider.toUpperCase()}/><Metric label="Feed status" value={dashboard.provider_status.status}/><Metric label="Delay" value={`${dashboard.provider_status.delay_seconds}s`}/><Metric label="Paper equity" value={`$${Number(dashboard.paper_account.equity).toLocaleString()}`}/><Metric label="Kill switch" value={dashboard.paper_account.kill_switch?'ON':'ready'}/></Card><Card title="Liquidity Map"><LiquidityMap levels={dashboard.levels}/></Card><Card title="Decision State">{dashboard.no_trade?<div className="no-trade">NO TRADE<span>Capital protected. No rules qualified.</span></div>:<div className="qualified">QUALIFIED SETUPS<span>Rules passed; execution remains paper-only.</span></div>}<p>{dashboard.news_warning}</p></Card></div>
    <Card id="structured" title={`Structured Setups · ${dashboard.normal_setups.length}`}>{dashboard.normal_setups.length===0?<p>No qualifying structured setups.</p>:dashboard.normal_setups.map(s=><article className="setup" key={`${s.symbol}-${s.name}`}><div><span className="tag">{s.symbol} · {s.direction}</span><h3>{s.name}</h3><p>{s.confluences.join(' · ')}</p></div><div className="trade-grid"><Metric label="Grade" value={s.grade}/><Metric label="Trigger" value={s.entry_trigger}/><Metric label="Invalidation" value={s.invalidation}/><Metric label="Target 1 / 2" value={`${s.target1} / ${s.target2}`}/><Metric label="Reward : risk" value={`${s.reward_risk}:1`}/><Metric label="Matching contract" value={s.contract?.option_symbol ?? 'none'}/></div></article>)}</Card>
    <Card id="lottery" title={`Lottery Lab · ${dashboard.lottery_setups.length}`} danger><div className="risk-warning"><strong>Highly speculative. Most lottery contracts are expected to expire worthless.</strong><span>Maximum modeled loss is the full debit shown. Estimates are not guarantees.</span></div>{dashboard.lottery_setups.length===0?<p>No lottery candidates.</p>:dashboard.lottery_setups.map(l=><article className="lotto" key={`${l.symbol}-${l.strike}-${l.right}`}><div><span className="tag orange">{l.symbol} {l.right.toUpperCase()} {l.strike}</span><h3>Momentum runner · score {l.setup_score}</h3><p>{l.explanation}</p></div><div className="trade-grid"><Metric label="Bid / ask" value={`${l.bid} / ${l.ask}`}/><Metric label="Maximum loss" value={`$${l.total_debit}`}/><Metric label="Spread" value={`${l.spread_percent}%`}/><Metric label="Delta / gamma" value={`${l.delta} / ${l.gamma}`}/><Metric label="Trigger / invalid" value={`${l.underlying_trigger} / ${l.underlying_invalidation}`}/><Metric label="2x / 5x / 10x est." value={`${l.estimated_2x_underlying} / ${l.estimated_5x_underlying} / ${l.estimated_10x_underlying}`}/></div><ul>{l.worthless_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></article>)}</Card>
    <div className="grid"><Card id="charts" title="Chart Workspace"><div className="chart-placeholder"><span>1m MOCK PRICE</span><svg viewBox="0 0 400 120" role="img" aria-label="Mock SPY trend"><polyline points="0,95 35,85 70,91 105,62 140,72 175,52 210,57 245,31 280,42 320,19 360,26 400,8"/></svg><EqualLevelOverlays levels={dashboard.levels}/></div></Card><Card id="journal" title={`Signal Journal · ${journal.length}`}>{journal.length===0?<p>Run the seed command to create sample signals.</p>:journal.slice(0,6).map(row=><div className="journal-row" key={row.id}><span>{row.symbol}</span><strong>{row.signal_type.replace('_',' ')}</strong><small>{row.status}</small></div>)}</Card><Card id="analytics" title="Seeded Paper Analytics">{analytics&&<><div className="analytics-grid"><Metric label="Samples" value={analytics.sample_size}/><Metric label="Win rate" value={`${analytics.win_rate}%`}/><Metric label="Profit factor" value={analytics.profit_factor ?? 'N/A'}/><Metric label="Expectancy" value={`${analytics.expectancy}%`}/></div><p>{analytics.message}</p><small>Minimum sample size: {analytics.minimum_sample_size}; promising: {analytics.statistically_promising?'yes':'no'}.</small></>}</Card></div>
    <footer>Paper-only research system · Provider: mock · No brokerage adapter or order-routing path exists.</footer>
  </main>;
}

const root=document.getElementById('root');
if(root) createRoot(root).render(<App/>);
