export interface ProviderStatus { provider:string; mode:string; status:string; delay_seconds:number; latest_timestamp:string; message:string }
export interface Quote { symbol:string; price:number; timestamp:string }
export interface Contract { option_symbol:string; bid:number; ask:number; volume:number; open_interest:number; delta:number|null; gamma:number|null }
export interface Setup { symbol:string; name:string; direction:string; grade:string; score:number; entry_trigger:number; invalidation:number; target1:number; target2:number; reward_risk:number; contract:Contract|null; confluences:string[] }
export interface Lottery { symbol:string; right:string; strike:number; bid:number; ask:number; midpoint:number; total_debit:number; spread_percent:number; delta:number|null; gamma:number|null; underlying_trigger:number; underlying_invalidation:number; break_even:number; estimated_2x_underlying:number; estimated_5x_underlying:number; estimated_10x_underlying:number; setup_score:number; explanation:string; worthless_reasons:string[] }
export interface LiquidityLevels { previous_day_high:number; previous_day_low:number; opening_range_high:number; opening_range_low:number; session_high:number; session_low:number; vwap:number; equal_highs:number[]; equal_lows:number[] }
export interface Dashboard { provider_status:ProviderStatus; quotes:Quote[]; market_session:string; volatility_proxy:number|null; levels:Record<string,LiquidityLevels>; directional_bias:Record<string,string>; news_warning:string; normal_setups:Setup[]; lottery_setups:Lottery[]; no_trade:boolean; paper_account:Record<string,string|number|boolean> }
export interface JournalSignal { id:number; symbol:string; signal_type:string; status:string; generated_at:string; payload:Record<string,unknown> }
export interface Analytics { minimum_sample_size:number; sample_size:number; statistically_promising:boolean; win_rate:number; profit_factor:number|null; average_winner:number; average_loser:number; expectancy:number; message:string }
