from abc import ABC, abstractmethod
from app.schemas.market import CandleOut, OptionContractOut, ProviderStatus, Quote

class MarketDataProvider(ABC):
    @abstractmethod
    def status(self) -> ProviderStatus: ...
    @abstractmethod
    def quotes(self, symbols: list[str]) -> list[Quote]: ...
    @abstractmethod
    def candles(self, symbol: str, timeframe: str = "1m") -> list[CandleOut]: ...
    @abstractmethod
    def option_chain(self, symbol: str) -> list[OptionContractOut]: ...
